package org.smojol.toolkit.task;

public enum CommandLineAnalysisTask {
    INJECT_INTO_NEO4J,
    EXPORT_TO_GRAPHML,
    WRITE_RAW_AST,
    WRITE_FLOW_AST,
    DRAW_FLOWCHART,
    EXPORT_MERMAID,
    WRITE_CFG,
    ATTACH_COMMENTS,
    WRITE_DATA_STRUCTURES,
    BUILD_PROGRAM_DEPENDENCIES,
    EXPORT_UNIFIED_TO_JSON,
    COMPARE_CODE,
    SUMMARISE_THROUGH_LLM,
    BUILD_PSEUDOCODE_GRAPH,
    ANALYSE_CONTROL_FLOW,
    BUILD_TRANSPILER_MODEL,
    GENERATE_IR
}
