package com.mojo.algorithms.task;

public enum CommandLineAnalysisTask {
    FLOW_TO_NEO4J,
    FLOW_TO_GRAPHML,
    WRITE_RAW_AST,
    WRITE_FLOW_AST,
    DRAW_FLOWCHART,
    EXPORT_MERMAID,
    WRITE_CFG,
    ATTACH_COMMENTS,
    WRITE_DATA_STRUCTURES,
    BUILD_PROGRAM_DEPENDENCIES,
    EXPORT_UNIFIED_TO_JSON,
    COMPARE_CODE,
    WRITE_LLM_SUMMARY,
    SUMMARISE_THROUGH_LLM,
    BUILD_TRANSPILER_FLOWGRAPH,
    BUILD_BASE_ANALYSIS,
    DO_NOTHING
}
