class ParameterConstants:
    TEXT_EMBEDDINGS_MODEL_PATH = "text_embeddings_model_path"
    CAPABILITIES_PATH = "capabilities_path"
    DS_INPUT_PATH = "data_structures_input_path"
    FLOW_AST_PATH = "flow_ast_path"
    UNIFIED_MODEL_PATH = "unified_model_path"
    GLOSSARY_OUTPUT_PATH = "output_path"
    PARAGRAPH_CAPABILITIES_OUTPUT_PATH = "paragraph_capabilities_output_path"
    PARAGRAPH_VARIABLES_EXPLANATIONS_OUTPUT_PATH = "paragraph_variables_explanations_output_path"
    RAW_AST_PATH = "raw_ast_path"
    VARIABLE_STATIC_VALUES_OUTPUT_PATH = "output"
