/* Generated by           cobc 3.2.0 */
/* Generated from         improper-goto.cbl */
/* Generated at           Oct 06 2024 02:19:02 */
/* GnuCOBOL build date    Jul 28 2023 18:42:18 */
/* GnuCOBOL package date  Jul 28 2023 17:02:56 UTC */
/* Compile command        cobc -C improper-goto.cbl */

#include <string.h> /* for memcpy, memcmp and friends */
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"improper-goto.cbl"
#define  COB_PACKAGE_VERSION		"3.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Oct 06 2024 02:19:02"
#define  COB_MODULE_DATE		20241006
#define  COB_MODULE_TIME		21902

/* Global variables */
#include "improper-goto.c.h"

/* Function prototypes */

COB_EXT_EXPORT int		IMPROPER__GOTO (void);
static int		IMPROPER__GOTO_ (const int);
static void		IMPROPER__GOTO_module_init (cob_module *module);

/* Functions */

static void gc_module_so_init () __attribute__ ((constructor));
static void gc_module_so_init ()
{
  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);
}

/* PROGRAM-ID 'IMPROPER-GOTO' */

/* ENTRY 'IMPROPER__GOTO' */

int
IMPROPER__GOTO ()
{
  return IMPROPER__GOTO_ (0);
}

static int
IMPROPER__GOTO_ (const int entry)
{
  /* Program local variables */
  #include "improper-goto.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 10        : Entry     IMPROPER-GOTO           : improper-goto.cbl */
  l_2:;

  /* Line: 10        : Section   R                       : improper-goto.cbl */

  /* Line: 11        : Paragraph RA1                     : improper-goto.cbl */

  /* Line: 12        : DISPLAY            : improper-goto.cbl */
  cob_display (0, 1, 1, &c_1);

  /* Line: 13        : PERFORM            : improper-goto.cbl */
  /* PERFORM S */
  frame_ptr++;
  frame_ptr->perform_through = 5;
  frame_ptr->return_address_ptr = &&l_11;
  goto l_5;
  l_11:
  frame_ptr--;

  /* Line: 14        : Section   S                       : improper-goto.cbl */
  l_5:;

  /* Line: 15        : Paragraph SA1                     : improper-goto.cbl */
  l_6:;

  /* Line: 16        : DISPLAY            : improper-goto.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 17        : IF                 : improper-goto.cbl */
  if (((int)cob_cmp_numdisp (b_17, 9, 5LL, 0) == 0))
  {

    /* Line: 18        : GO TO              : improper-goto.cbl */
    goto l_6;
  }

  /* Line: 19        : PERFORM            : improper-goto.cbl */
  /* PERFORM SZ1 */
  frame_ptr++;
  frame_ptr->perform_through = 8;
  frame_ptr->return_address_ptr = &&l_12;
  goto l_8;
  l_12:
  frame_ptr--;

  /* Line: 20        : Paragraph SE1                     : improper-goto.cbl */

  /* Line: 21        : DISPLAY            : improper-goto.cbl */
  cob_display (0, 1, 1, &c_3);

  /* Line: 22        : STOP RUN           : improper-goto.cbl */
  cob_stop_run (b_2);

  /* Line: 23        : Paragraph SZ1                     : improper-goto.cbl */
  l_8:;

  /* Line: 24        : DISPLAY            : improper-goto.cbl */
  cob_display (0, 1, 1, &c_4);

  /* Line: 25        : GO TO              : improper-goto.cbl */
  goto l_9;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 26        : Paragraph SZ2                     : improper-goto.cbl */
  l_9:;

  /* Line: 27        : DISPLAY            : improper-goto.cbl */
  cob_display (0, 1, 1, &c_5);

  /* Line: 28        : Paragraph SZ3                     : improper-goto.cbl */

  /* Line: 29        : EXIT               : improper-goto.cbl */

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 5)
    goto *frame_ptr->return_address_ptr;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  IMPROPER__GOTO_module_init (module);

  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->xml_code = NULL;
  module->xml_event = NULL;
  module->xml_information = NULL;
  module->xml_namespace = NULL;
  module->xml_namespace_prefix = NULL;
  module->xml_nnamespace = NULL;
  module->xml_nnamespace_prefix = NULL;
  module->xml_ntext = NULL;
  module->xml_text = NULL;
  module->json_code = NULL;
  module->json_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  /* initialize field RETURN-CODE */
  b_2 = 0;

  /* initialize field WS-NUM1 */
  memcpy (b_17, "000000005", 9);


  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
    return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:
  return 0;

}

/* End PROGRAM-ID 'IMPROPER-GOTO' */

/* Initialize module structure for IMPROPER-GOTO */
static void IMPROPER__GOTO_module_init (cob_module *module)
{
  module->module_name = "IMPROPER-GOTO";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->gc_version = COB_PACKAGE_VERSION;
  module->module_entry.funcptr = (void *(*)())IMPROPER__GOTO;
  module->module_cancel.funcptr = (void *(*)())IMPROPER__GOTO_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->xml_mode = 1;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

